import { pressStartP2, rajdhani } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Pokenext",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-br"
      className={`${pressStartP2.variable} ${rajdhani.variable}`}
    >
      <body className="h-[100vh] bg-zinc-950 border-red-500">{children}</body>
    </html>
  );
}
